# =============================================================================
# Pooled predicted values from MICE
# earlycapistran@comunidad.unam.mx - March 2021
# =============================================================================

#' Calculates pooled predicted values from muliptly imputed repeated analyses
#' from MICE.
#'
#' @param mira A 'mira' object generated by MICE
#' @return A datafram
#' @examples 
#' getPooledPreds(my_mira_object)

getPooledPreds <- function(mira) {
  require(broom)
  require(mice)
  if (!is.mira(mira)) 
    stop("The object must have class 'mira'")
  # Calculate predictions from m imputed models
  predList <- lapply(mira$analyses, augment)
  # Make a dataframe of fitted values from each model
  predListDf <- as.data.frame(lapply(predList, `[`, ".fitted"))
  means <- apply(predListDf, 1, mean)

  # Extract a variable with predictor data
  predVar <- predList[[1]][,1]
  
  result <- data.frame(predVar, means)
  print(result)
  return(result)
}